### ISSUE TITLE
Exception Access Violation

### ISSUE THREAD

**Issue by Laezor** [Linux-BFME/Installers#8]
As the title says, its for BFME 1. 

Wine version: 
![image](https://user-images.githubusercontent.com/32393101/162591903-6dff00f1-6527-4f43-a990-fd7b3be08d06.png)

Occurs: the error starts not when I alt+tab out of the game, but it seems when I go in the game again. Game goes to a black screen, error is in the background, the music continues to play in the background.

**Comment by dginovker** [comment]
This one is out of our control, use virtual desktops or windowed mode if you want to do other things while playing
